alert("Программа для нахождения суммы, разности, произведения и частностного их квадратов")
alert("Введённые числа должны быть > 0")
var number1 = prompt("Введите первое число: ")
number1 = parseFloat(number1)
var number2 = prompt("Введите второе число: ")
number2 = parseFloat(number2)
var summ = (number1**2)+(number2**2)
var difference = (number1**2)-(number2**2)
var multiplication = (number1**2)*(number2**2)
var division = (number1**2)/(number2**2)
alert("Сумма: "+summ)
alert("Разность: "+difference)
alert("Произведение: "+multiplication)
alert("Частное: "+division)